name: Update Lists
on:
  schedule:
    - cron:  '0 * * * *'

  repository_dispatch:

jobs:
  update-lists:
    name: update-lists
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Update Lists
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        poetry install
        poetry run letterboxd-to-gist --access-token $ACCESS_TOKEN --gist-id $GIST_ID
