name: Update Lists
on:
  schedule:
    - cron:  '0 * * * *'

  repository_dispatch:

jobs:
  update-lists:
    name: update-lists
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.0
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.1.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      with:
        python_version: 3.8.0
        poetry_version: 1.0.0
        args: run letterboxd-to-gist --access-token $ACCESS_TOKEN --gist-id $GIST_ID